shakenfist_client/apiclient.py
=> Pass console data length in the correct way.

shakenfist_client/main.py
=> Fix all option and network create name order

shakenfist_client/main.py
=> Remove small memory transition special case.

shakenfist_client/main.py
=> Handle empty fields in returned instances.

shakenfist_client/main.py
=> Fix network events output in simple format.

shakenfist_client/main.py
Fixes #32. Depends on shakenfist#691 landing first.
=> Show network state in network listings.

shakenfist_client/main.py
The new functionality broke the client. Fixes #49.
=> Handle interfaces with no address assigned.

shakenfist_client/apiclient.py, shakenfist_client/main.py, shakenfist_client/tests/test_client_apiclient.py
Also, make verbose logging work. Fixes #48. Fixes #49.
=> General client bug fixes.

shakenfist_client/apiclient.py, shakenfist_client/main.py
=> Actually update labels.

ansible/sf_instance.py, ansible/sf_network.py, shakenfist_client/apiclient.py
Also a bug fix in the API client.
Closes #78
=> Add namespace parameter to ansible module

ansible/sf_instance.py, ansible/sf_network.py, shakenfist_client/apiclient.py
There were some logic errors in the sf_instance changes, and it turns out we also need async in sf_networks for this to make sense.
=> Fix typos in sf_instance and add async support to sf_network.

ansible/sf_instance.py, ansible/sf_network.py
=> Additional namespace fixes.

shakenfist_client/commandline/instance.py
Closes #95 
```
$ sf-client  --simple instance list
uuid,name,namespace,cpus,memory,hypervisor,power state,state,interfaces
5426afc8-907f-4627-9790-47e935da8a8a,andynet,system,1,1024,sf-2,on,created,0:10.0.0.183(192.168.10.63)
b63d686c-30e3-442e-ae09-57ebcf4beb37,andy,system,1,1024,sf-3,on,created,
e7d980af-6665-4578-ba0d-720d81d10ddd,andy1,system,1,1024,sf-2,on,created,0:10.0.0.250
f893c180-a1fa-4cf4-88b5-ae109cb671d9,andynet,system,1,1024,sf-2,on,created,0:10.0.0.191
fb9c4e07-a3b6-43c3-a529-0e0f919279d0,andynet,system,1,1024,sf-2,on,created,0:10.0.0.179(192.168.10.205);1:10.0.0.216(192.168.10.96)
fbce0e4c-78df-4b77-b0a2-930b8895eb51,andynet,system,1,1024,sf-3,on,created,
```
I've left the extra interface information in the JSON output since this is usually read by a machine and can be …
=> Add interfaces to instance list JSON output

Jenkinsfile-debian-10-slim-primary, requirements.txt, shakenfist_client/apiclient.py, shakenfist_client/commandline/artifact.py
This is a prototype, but works for my current needs.
=> Client side implementation of artifact upload.

shakenfist_client/apiclient.py, shakenfist_client/commandline/artifact.py, shakenfist_client/commandline/label.py, shakenfist_client/main.py
Depends on https://github.com/shakenfist/shakenfist/pull/976
=> Implement client for artifact show and versions.

shakenfist_client/apiclient.py
Depends on https://github.com/shakenfist/shakenfist/pull/1089
=> Delete the correct artifact.

shakenfist_client/apiclient.py, shakenfist_client/commandline/artifact.py
The server has been doing this between nodes for a while.
Depends on https://github.com/shakenfist/shakenfist/pull/1077
=> Support downloading artifacts in the client.

ansible/sf_instance.py, shakenfist_client/apiclient.py, shakenfist_client/commandline/instance.py, shakenfist_client/tests/test_client_apiclient.py
(Also cleanup the help for "instance create").
=> Add support for new instance arguments.

shakenfist_client/apiclient.py, shakenfist_client/commandline/instance.py, shakenfist_client/tests/test_client_apiclient.py
Depends on shakenfist/shakenfist#1134
=> Handle instance tags and instance cpu affinity

shakenfist_client/apiclient.py, shakenfist_client/commandline/artifact.py, shakenfist_client/commandline/instance.py, shakenfist_client/tests/test_client_apiclient.py
Plays along with https://github.com/shakenfist/shakenfist/pull/1208.
=> Client side support for thin snapshots.

shakenfist_client/apiclient.py
Depends on https://github.com/shakenfist/shakenfist/pull/1236
=> JSON is why our indexes were strings not ints.

.github/workflows/python-unit-tests.yml, AUTHORS, Jenkinsfile-debian-11-slim-primary, shakenfist_client/apiclient.py, shakenfist_client/commandline/instance.py, shakenfist_client/tests/test_client_apiclient.py
Additionally, add the sf-agent to CI jobs.
=> Implement side channel support in the client.
